---
abstract: 'Use Moo methods as functions with an implicit singleton'
author:
  - 'Robert Rothenberg <rrwo@cpan.org>'
build_requires:
  Moo: '0'
  Test::Most: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-NonOO
recommends:
  Package::Stash::XS: '0'
requires:
  Package::Stash: '0'
  perl: '5.009003'
resources:
  bugtracker: https://github.com/robrwo/MooX-NonOO/issues
  repository: git://github.com/robrwo/MooX-NonOO.git
version: v0.1.0
